[package]
name = "user"
version = "0.1.0"
edition = "2021"

[dependencies]
panic-halt = "0.2.0"

[lib]
name = "xv6rs_user"
path="src/lib.rs"
crate-type = ["staticlib", "rlib"] # Creates static lib

[[bin]]
name="sleep"
path="src/sleep.rs"

